---
- name: Generate Join command
  hosts: all 
  gather_facts: true
  vars: 
    node_details: "{{ ansible_facts['nodename'].split('-') }}"
  vars_files: 
    - vars/all.yaml
  tasks: 
    - block: 
        - name: Check cluster status
          shell: kubectl cluster-info
          register: cluster_info
          retries: 5
          delay: 180 
          until: "'running' in cluster_info.stdout"
        
        - name: Generate new token and print join command
          shell: 'kubeadm token create --print-join-command'
          register: join_token
        
        - name: generate certificate key for control plane
          shell: 'kubeadm init phase upload-certs --upload-certs 2>/dev/null | tail -1'
          register: master_certificate_key
        
        - name: stats/token for master and worker nodes
          set_stats:
            data: 
              "{{ node_details[0] }}_{{ node_details[2] }}_{{ node_details[3][-2:] }}_master_cert_key": "{{ master_certificate_key.stdout }}"
              "{{ node_details[0] }}_{{ node_details[2] }}_{{ node_details[3][-2:] }}_join_token": "{{ join_token.stdout }}"
              "{{ node_details[0] }}_{{ node_details[2] }}_{{ node_details[3][-2:] }}_host": "{{ ansible_facts['nodename'] }}"
      become: true

      rescue: 
        - name: Final statement on generating token from control plane
          debug: 
            msg: "unable to generate the token and we are unable to connect to the host"  

  