---
- name: Generate Join command
  hosts: control
  gather_facts: true
  become: true
  tasks: 
    - name: Check cluster status
      shell: kubectl cluster-info
      register: cluster_info
      retries: 5
      delay: 180 
      until: "'running' in cluster_info.stdout"
        
    - name: Generate new token and print join command
      shell: 'kubeadm token create --print-join-command'
      register: k8s_join_cmd
        
    - name: generate certificate key for control plane
      shell: 'kubeadm init phase upload-certs --upload-certs 2>/dev/null | tail -1'
      register: master_certificate_key

- name: Add new worker nodes
  hosts: workers
  gather_facts: true
  vars_files: 
    - vars/worker-node-vars.yaml
  tasks:
    - name: Run tasks for wrkrc4 node 
      vars: 
        join_token: "{{ hostvars['Master1']['k8s_join_cmd']['stdout'] }}"
      import_role: 
        name: k8s_worker_node_1
      become: true
      register: status

- name: Approve Pending CSR and label addition to the nodes 
  hosts: control 
  gather_facts: yes 
  vars_files: 
    - vars/main.yaml
  tasks: 
    - block: 
        - name: Get CSR certs to be approved
          shell: kubectl get csr --no-headers | grep -iv Approved | awk '{ print$1 }'
          register: certs 
          become: true
          delegate_facts: true

        - debug: var=certs

        - name: Approve CSR certs 
          shell: kubectl certificate approve {{ item }}
          with_items: "{{ certs.stdout_lines }}"
          become: true
          delegate_facts: true

        
        - name: Fetch node details without k8s labels
          shell:
            kubectl get nodes --no-headers -o custom-columns=Name:.metadata.name | while read node; do 
              if ! kubectl get node "$node" --show-labels | grep -q "kubernetes-host=" ; then
                echo "$node"
              fi 
            done 
          register: unlabelled_nodes
          become: true
          delegate_facts: true

        - debug: var=unlabelled_nodes

        - name: Add the kubernetes-host label to unlabelled_nodes
          shell: kubectl label nodes {{ item }} kubernetes-host= 
          with_items: "{{ unlabelled_nodes.stdout_lines }}"
          become: true 
          delegate_facts: true



